# This file is generated by gyp; do not edit.


LOCAL_PATH := $(call my-dir)
GYP_CONFIGURATION ?= Debug
GYP_VAR_PREFIX ?=
GYP_HOST_VAR_PREFIX ?=
GYP_HOST_MULTILIB ?=
$(info DEBUG : PRE11!)
include $(LOCAL_PATH)/android_webview/android_webview_common.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/android_webview/android_webview_jarjar_content_resources.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/android_webview/android_webview_jarjar_ui_resources.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/android_webview/android_webview_pak.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/android_webview/android_webview_resources.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/android_webview/android_webview_strings_grd.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/android_webview/libwebviewchromium.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/android_webview/native/android_webview_native_jni.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/android_webview/native/cancellation_signal_android_jar_jni_headers.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/android_webview/native/webview_native.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/v8/tools/gyp/js2c.host.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/v8/tools/gyp/mksnapshot.host.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/v8/tools/gyp/v8.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/v8/tools/gyp/v8_base.host.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/v8/tools/gyp/v8_base.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/v8/tools/gyp/v8_libbase.host.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/v8/tools/gyp/v8_libbase.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/v8/tools/gyp/v8_libplatform.host.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/v8/tools/gyp/v8_nosnapshot.host.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/v8/tools/gyp/v8_snapshot.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/third_party/icu/icudata.host.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/third_party/icu/icui18n.host.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/third_party/icu/icui18n.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/third_party/icu/icuuc.host.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/third_party/icu/icuuc.target.$(HOST_OS)-$(TARGET_ARCH).mk
include $(LOCAL_PATH)/third_party/icu/system_icu.target.$(HOST_OS)-$(TARGET_ARCH).mk

# "gyp_all_modules" is a concatenation of the "gyp_all_modules" targets from
# all the included sub-makefiles. This is just here to clarify.
gyp_all_modules:
